/**
 * Writes src/generated/contract.ts: the data of ../contract this package
 * carries (the layouts, the model table, the case folding table, the JSON
 * Schemas of what it writes and reads), so the
 * published package needs no file outside itself. `npm test` fails when
 * the file differs from what this writes (tests/contract-data.test.ts).
 *
 *     node tools/generate.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
export const CONTRACT = join(here, "..", "..", "contract");
export const OUT = join(here, "..", "src", "generated", "contract.ts");

const read = (p: string) => JSON.parse(readFileSync(join(CONTRACT, p), "utf8"));

export function generate(): string {
  const layouts = { xml: read("layouts/xml.json"), chat: read("layouts/chat.json"), json: read("layouts/json.json") };
  const models = read("models.json");
  const folds = read("unicode/casefold.json");
  const schemas = Object.fromEntries(["call", "event", "interface", "rating", "saved"].map((n) => [n, read(`schema/${n}.schema.json`)]));
  return [
    "// Generated by tools/generate.ts from ../contract: do not edit. Run `node tools/generate.ts`.",
    "",
    `/** The layouts (contract/layouts/*.json): lmcc adapter artifacts. */`,
    `export const LAYOUTS: Record<"xml" | "chat" | "json", Record<string, unknown>> = ${JSON.stringify(layouts)};`,
    "",
    `/** What a model can do, by provider (contract/models.json). */`,
    `export const MODELS = ${JSON.stringify(models)} as const;`,
    "",
    `/** Unicode ${folds.unicode} full case folding (contract/unicode/casefold.json): code point (hex) → folded text. */`,
    `export const CASEFOLD: Record<string, string> = ${JSON.stringify(folds.folds)};`,
    "",
    `/** The JSON Schemas (contract/schema/*.schema.json), by name: what every record, event, interface and manifest must pass. */`,
    `export const SCHEMAS: Record<"call" | "event" | "interface" | "rating" | "saved", Record<string, unknown>> = ${JSON.stringify(schemas)};`,
    "",
  ].join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(OUT, generate());
  console.log(`wrote ${OUT}`);
}
