"""Reinforcement learning and distillation on Prime Intellect, for an AI function.

    env = functai.bake.prime.env_package(classify, rows, "envs/classify", name="classify-rows")
    #   prime env push -p envs/classify          (the Environments Hub)
    toml = functai.bake.prime.config(classify, env="me/classify-rows", model="Qwen/Qwen3.5-0.8B", loss="rl")
    #   prime train classify.toml                 (hosted training; billed by Prime)

The environment package holds the function as a saved program (``functai.save``:
its code, layout, instruction, demos and pinned requirements, verified to
load on its own) and the rows, one task per row, rewarded by exact match with
the row's expected outputs (``functai-rows``). Rollouts run through the
``functai-verifiers`` harness, so the model is called with the function's
lmcc layout and every multi-turn rollout stays one training sample.

- ``loss="rl"``: the model is trained on its own rollouts, rewarded by the rows.
- ``loss="sft"`` with ``teacher=``: distillation; the teacher answers through
  the same layout, its reasoning dropped before recording, and the student
  learns the answer only.

The trained model is served by Prime; call it from functai with its model name
and the same layout (``fn.using(lm=..., adapter=<the layout used>)``).
"""

from __future__ import annotations

import json
import re
import shutil
import textwrap
from pathlib import Path
from typing import Any, Dict, Optional


def _toml_value(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return json.dumps(v)
    if isinstance(v, dict):
        return "{ " + ", ".join(f"{k} = {_toml_value(x)}" for k, x in v.items()) + " }"
    if isinstance(v, (list, tuple)):
        return "[" + ", ".join(_toml_value(x) for x in v) + "]"
    raise TypeError(f"{type(v).__name__} has no TOML form")


def _module_name(name: str) -> str:
    mod = re.sub(r"[^0-9a-zA-Z_]", "_", name).lower()
    return mod if mod[:1].isalpha() else f"env_{mod}"


def env_package(program: Any, rows: Any, path: "str | Path", *, name: str, version: str = "0.1.0",
                overwrite: bool = False, **save_options) -> Path:
    """Write a verifiers environment package for ``program`` (an @ai function) and
    ``rows`` (a list of dicts, or any table functai reads): the saved program,
    the rows as JSON lines, a taskset (one task per row, reward ``agrees``) and
    a ``pyproject.toml``. ``save_options`` go to ``functai.save`` (``include``,
    ``requires``, ``allow``, ``record``). Returns the package folder, ready for
    ``prime env push -p <folder>``."""
    import functai
    from ..evaluation import rows_of
    root = Path(path).expanduser().resolve()
    if root.exists():
        if not overwrite:
            raise FileExistsError(f"{root} exists; env_package(..., overwrite=True) replaces it")
        shutil.rmtree(root)
    mod = _module_name(name)
    pkg = root / mod
    pkg.mkdir(parents=True)
    report = functai.save(program, pkg / "saved", **save_options)
    data = rows_of(rows)
    from lmcc.turn import to_json
    (pkg / "rows.jsonl").write_text("".join(json.dumps(to_json(r), ensure_ascii=False) + "\n" for r in data))
    fn_name = program.__name__
    (pkg / "program.py").write_text(textwrap.dedent(f'''\
        """The saved AI function this environment trains (loaded from ./saved)."""

        from pathlib import Path

        import functai

        {fn_name} = functai.load(Path(__file__).parent / "saved", trust=True)
        '''))
    (pkg / "__init__.py").write_text(textwrap.dedent(f'''\
        """{name}: {fn_name} over rows.jsonl, one task per row, rewarded by exact match (functai-rows)."""

        from collections.abc import Iterator
        from pathlib import Path

        import verifiers.v1 as vf

        from functai_rows import RowsConfig, RowsEnv, RowsTask, row_tasks

        __all__ = ["Env", "Taskset"]


        class Config(RowsConfig):
            program: str = "{mod}.program:{fn_name}"
            data: str = str(Path(__file__).parent / "rows.jsonl")


        class Taskset(vf.Taskset[RowsTask, Config]):
            def load(self) -> Iterator[RowsTask]:
                return row_tasks(self.config)


        class Env(RowsEnv):
            pass
        '''))
    requirements = [r for r in (pkg / "saved" / "requirements.txt").read_text().splitlines() if r.strip()]
    deps = sorted(set(["functai[prime]"] + [r for r in requirements if not r.startswith("functai")]))
    (root / "pyproject.toml").write_text(textwrap.dedent(f'''\
        [project]
        name = "{name}"
        version = "{version}"
        description = "{fn_name} over its rows, for verifiers / Prime Intellect (generated by functai)"
        requires-python = ">=3.11"
        dependencies = {_toml_value(deps)}

        [build-system]
        requires = ["hatchling"]
        build-backend = "hatchling.build"

        [tool.hatch.build.targets.wheel]
        packages = ["{mod}"]
        '''))
    local = [r for r in report.requirements.values() if r.local_path]
    if local:
        (root / "LOCAL.txt").write_text(
            "This package's saved program depends on packages installed from folders on the machine that wrote\n"
            "it; Prime's workers cannot install those until they are published:\n"
            + "".join(f"  {r.distribution} ({r.local_path})\n" for r in local))
    return root


def config(program: Any, *, env: str, model: str, loss: str = "rl", teacher: Optional[str] = None,
           adapter: Optional[str] = None, max_steps: int = 100, batch_size: int = 128,
           rollouts_per_example: Optional[int] = None, max_tokens: int = 1024, enable_thinking: bool = False,
           teacher_sampling: Optional[Dict[str, Any]] = None, split: Optional[str] = None,
           capabilities: Optional[Dict[str, bool]] = None, path: "str | Path | None" = None) -> str:
    """The ``prime train`` TOML for ``program`` on the Hub environment ``env``
    (``owner/name``, pushed from ``env_package``). ``loss``: ``"rl"`` or
    ``"sft"`` (distillation from ``teacher``). ``adapter``: the lmcc layout the
    model is called with (a name in the program module's ADAPTERS, functai's
    "xml"/"chat", or an adapter JSON path); None: the function's own. Written to
    ``path`` when given; returned either way."""
    if loss not in ("rl", "sft"):
        raise ValueError(f"loss is 'rl' or 'sft', not {loss!r}")
    if loss == "sft" and teacher is None:
        raise ValueError("loss='sft' distills a teacher: pass teacher='<model>'")
    mod = _module_name(env.split("/")[-1])
    harness: Dict[str, Any] = {"id": "functai-verifiers", "program": f"{mod}.program:{program.__name__}"}
    if adapter is not None:
        harness["adapter"] = adapter
    if capabilities is not None:
        harness["capabilities"] = capabilities
    taskset: Dict[str, Any] = {"id": env}
    if split is not None:
        taskset["split"] = split
    lines = [f"# {program.__name__} on {env}: {'reinforcement learning' if loss == 'rl' else f'distilling {teacher}'}"
             f" (generated by functai)", "#", "#   prime train <this file>", ""]
    lines += [f"model = {_toml_value(model)}"]
    if loss == "sft":
        lines += ['loss = "sft"']
    lines += [f"max_steps = {max_steps}", f"batch_size = {batch_size}",
              f"rollouts_per_example = {rollouts_per_example if rollouts_per_example is not None else (1 if loss == 'sft' else 8)}",
              ""]
    if teacher is not None:
        lines += ["[teacher]", f"model = {_toml_value(teacher)}", ""]
        if teacher_sampling:
            lines += ["[teacher.sampling]"] + [f"{k} = {_toml_value(v)}" for k, v in teacher_sampling.items()] + [""]
    lines += ["[sampling]", f"max_tokens = {max_tokens}", f"enable_thinking = {_toml_value(enable_thinking)}", "",
              "[[env]]", f"taskset = {_toml_value(taskset)}", f"harness = {_toml_value(harness)}", ""]
    text = "\n".join(lines)
    if path is not None:
        Path(path).write_text(text)
    return text


__all__ = ["env_package", "config"]
