"""Runs before every `quarto render` (see _quarto.yml, pre-render).

Writes the generated pages, never by hand:

- reference/*.qmd from the docstrings (quartodoc). In an "Examples"
  section, ```python blocks become executed cells, so every example on a
  reference page shows its real output, like pkgdown's.
- examples/*.qmd: one page per example folder, showing its rendered
  README.md (the examples render themselves; see tests/docs_live.py).
- news.qmd from CHANGELOG.md.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

DOCS = Path(__file__).resolve().parent
ROOT = DOCS.parent
REPO = "https://github.com/maximerivest/functai/blob/master"

EXAMPLES = [  # in the order of the gallery
    ("typing_and_extraction", "Types in, types out: lists, dicts, enums, literals, dataclasses, pydantic models."),
    ("docments_flexiclass", "Comments are prompts: on parameters, the return line, class fields and outputs."),
    ("claide_code", "A terminal assistant: a shell tool with an allow-list, and memory."),
    ("local_simple_rag_agent", "An agent that reads the web, a fact checker, and the same agent on a local model."),
    ("graph_rag", "A knowledge graph built chunk by chunk with pydantic models, then queried."),
    ("modules", "A multi-hop fact checker as one @module: evaluated, optimized, run on a table."),
    ("optimizing_translator", "English to Québécois French: an AI judge as the metric, InstructionSearch, before and after."),
    ("tracking_and_osb", "Observability: phistory, token usage, logged evaluation runs, the reply cache."),
]

SETUP_CELL = '''```{python}
#| include: false
import functai
from functai import *
functai.configure(lm="gpt-4.1-mini", temperature=0)
import polars as pl   # how tables print on this site: whole texts, all columns
pl.Config.set_fmt_str_lengths(90); pl.Config.set_tbl_cols(12); pl.Config.set_tbl_hide_dataframe_shape(True)
```

'''


def reference() -> None:
    subprocess.run([sys.executable, "-m", "quartodoc", "build", "--config", "_quarto.yml"],
                   cwd=DOCS, check=True, capture_output=True)
    # quarto skips files whose name starts with "_": the page of `_ai` gets another name
    ref = DOCS / "reference"
    if (ref / "_ai.qmd").exists():
        (ref / "_ai.qmd").replace(ref / "ai-sentinel.qmd")
        index = ref / "index.qmd"
        index.write_text(index.read_text().replace("](_ai.qmd", "](ai-sentinel.qmd"))
    pages = {p.stem for p in (DOCS / "reference").glob("*.qmd")}

    def see_also(m: re.Match) -> str:
        # numpy "name : why" lines become links, as on pkgdown pages
        def link(line: str) -> str:
            name, _, why = line.partition(" : ")
            head = name.split(".")[0]
            if name in pages:
                target = f"{name}.qmd"
            elif head in pages:
                target = f"{head}.qmd#functai.{name}"
            else:
                return f"- `{name}`: {why}"
            return f"- [`{name}`]({target}): {why}"
        lines = [link(l) for l in m.group(2).strip().splitlines() if l.strip()]
        return m.group(1) + "\n" + "\n".join(lines) + "\n\n"

    for page in (DOCS / "reference").glob("*.qmd"):
        if page.name == "index.qmd":
            continue
        text = page.read_text()
        text = re.sub(r"(^#+ See Also[^\n]*\n)(.*?)(?=^#)", see_also, text, flags=re.MULTILINE | re.DOTALL)
        page.write_text(text)
        m = re.search(r"^(#+) Examples[^\n]*\n", text, re.MULTILINE)
        if not m:
            continue
        level = len(m.group(1))
        end = re.search(rf"^#{{1,{level}}} ", text[m.end():], re.MULTILINE)
        stop = m.end() + end.start() if end else len(text)
        # a block whose first line is "# not run: <why>" stays as shown (R's \\dontrun)
        section = re.sub(r"```python\n(?!# not run)", "```{python}\n", text[m.end():stop])
        text = text[:m.end()] + section + text[stop:]
        # one hidden setup cell per page that runs code
        title_end = text.index("\n") + 1
        page.write_text(text[:title_end] + "\n" + SETUP_CELL + text[title_end:])


def examples() -> None:
    out = DOCS / "examples"
    out.mkdir(exist_ok=True)
    rows = []
    for name, blurb in EXAMPLES:
        readme = ROOT / "examples" / name / "README.md"
        text = readme.read_text()
        title = re.match(r"# (.+)\n", text).group(1)
        body = text[text.index("\n") + 1:]
        body = re.sub(r"Rendered from \[`main.qmd`\]\(main.qmd\);",
                      f"Rendered from [`examples/{name}/main.qmd`]({REPO}/examples/{name}/main.qmd);", body)
        body = body.replace("](main.qmd)", f"]({REPO}/examples/{name}/main.qmd)")
        page = (f'---\ntitle: "{title}"\ndescription: "{blurb}"\n---\n\n'
                f"<!-- generated by _prebuild.py from examples/{name}/README.md: edit main.qmd there -->\n\n"
                + body)
        (out / f"{name}.qmd").write_text(page)
        rows.append(f"[{title}]({name}.qmd)\n: {blurb}\n")
    (out / "index.qmd").write_text(
        '---\ntitle: "Examples"\ntoc: false\n---\n\n'
        "Each example solves one real problem from start to finish, with the\n"
        "real replies of real models. They assume you have read\n"
        "[Get started](../get-started.qmd).\n\n" + "\n".join(rows))


def news() -> None:
    text = (ROOT / "CHANGELOG.md").read_text()
    text = re.sub(r"^# Changelog\n", "", text)
    (DOCS / "news.qmd").write_text('---\ntitle: "News"\n---\n\n' + text)


if __name__ == "__main__":
    reference()
    examples()
    news()
